name: iobix
description: App for CINI (Colbits Integrated Network Infrastructure)
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.21+4

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  badges: ^2.0.2
  bubble_bottom_bar: ^2.0.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.1.3
  flutter_launcher_icons: ^0.9.2
  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^10.1.0
  get: ^4.6.1
  google_maps_flutter: ^2.1.3
  gsheets: ^0.4.2
  hex: ^0.2.0
  intl: ^0.17.0
  location: ^4.3.0
  modal_bottom_sheet: ^2.0.1
  path_provider: ^2.0.9
  percent_indicator: 4.0.1
  share: ^2.0.4
  syncfusion_flutter_gauges: ^19.4.56

dev_dependencies:
  flutter_switch: ^0.3.2
  flutter_test:
    sdk: flutter
  led_bulb_indicator: ^0.0.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/512.png'

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/login/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
